# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       pattern-example

# >> macros
# << macros
%define pattern_name example

Summary:    Provides pattern '%{name}'
Version:    1
Release:    1
Group:      Packaging/Patterns
License:    GPLv2
Source0:    pattern-%{pattern_name}-%{version}.tar.xz
Source100:  pattern-example.yaml
BuildRequires:  repomd-pattern-builder
Provides:   package-groups

%description
%{summary}.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_datadir}/package-groups/*.xml
# >> files
# << files
